[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/tournaments"
  to = "/tournaments.html"
  status = 200
  force = false

[[redirects]]
  from = "/index"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false